# Configuração específica para Dockploy
version: '1.0'

build:
  dockerfile: Dockerfile
  context: .

ports:
  - "8080:8080"

environment:
  - SPRING_PROFILES_ACTIVE=production
  - SERVER_PORT=8080
  - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/banco
  - SPRING_DATASOURCE_USERNAME=sa
  - SPRING_H2_CONSOLE_ENABLED=false
  - SPRING_JPA_SHOW_SQL=false

volumes:
  - data:/app/data

restart: unless-stopped

